### ISSUE TITLE
Hello @udaykamal20 thanks for the quick response. I belive that in order to run the code succesfully I need the Recurrent_3D_DenseUnet_model.h5 file. Do you happen to have it?

### ISSUE THREAD

**Issue by ldelaoa** [udday2014/Team_Spectrum#2]
Hello @udaykamal20 thanks for the quick response. I belive that in order to run the code succesfully I need the Recurrent_3D_DenseUnet_model.h5 file. Do you happen to have it?

_Originally posted by @ldelaoa in https://github.com/udaykamal20/Team_Spectrum/issues/1#issuecomment-1209071492_

**Comment by udaykamal20** [comment]
I have responded to the original issue so closing this one.
